language: python
python:
  - "2.7"
  - "3.3"

# commands to install with dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -e ."

# command to run tests
script: python -m pytest test/test_hello.py
