language: python
python:
  - "2.7"

# commands to install with dependencies
install:
  - "pip install pytest"
  - "pip install -e ."
  - "pwd"

# command to run tests
script: pytest test/test_hello.py
