language: python
matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial

# commands to install with dependencies
install:
  - "pip install --upgrade pip"
  - "pip install --upgrade pytest"
  - "pip install --upgrade --force-reinstall setuptools"
  - "pip install -e ."

# command to run tests
script: python -m pytest -v
