version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  Python_2.7:
    docker:
      - image: circleci/python:2.7
    steps: &steps
      - checkout
      - run: |
          pip install --upgrade pip
          pip install --upgrade pytest
          pip install --upgrade --force-reinstall setuptools
          pip install hcli_core
          pip install gunicorn==19.9.0
          pip install -e .
          python -m pytest -v
  Python_3.6:
      docker:
        - image: circleci/python:3.6
      steps: *steps

workflows:
  main:
    jobs
      - Python_2.7
      - Python_3.6
